# Generated by Django 2.2.24 on 2021-10-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('secondname', models.CharField(max_length=200)),
                ('emp_id', models.IntegerField()),
            ],
        ),
    ]
